import type { HeaderLink } from "#types";
import type { Metadata, Viewport } from "next";

import { env } from "#env";

export const APP_NAME = "Takhirov's Diary";
export const APP_TITLE_TEMPLATE = `%s </> ${APP_NAME}`;
export const APP_DESCRIPTION = "Portfolio and blog of Muhammaddiyor Tohirov — full‑stack TypeScript developer from Tashkent building production‑ready web platforms and Telegram bots with Node.js, React/Next.js, and Vue/Nuxt.";
export const SITE_URL = env.SITE_URL || "https://takhirov.uz";

export const HEADER_LINKS: HeaderLink[] = [
  { label: "Blog", href: "/blog" },
  { label: "Projects", href: "/projects" },
  { label: "Resume", href: "/resume" },
] satisfies HeaderLink[];

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  title: {
    default: APP_NAME,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  keywords: ["blog", "diary", "personal", "developer", "typescript", "react", "nextjs", "web development"],
  category: "blog",

  applicationName: APP_NAME,

  creator: "Muhammaddiyor Takhirov",
  authors: [{ name: "Muhammaddiyor Takhirov", url: "https://github.com/mtakhirov" }],
  generator: "Next.js",
  publisher: "Vercel",

  manifest: "/manifest.json",
  icons: {
    icon: "/favicon/favicon.ico",
    apple: "/favicon/apple-icon.png",
    shortcut: "/favicon.ico",
  },

  referrer: "origin",
  formatDetection: { telephone: true, address: true, email: true, date: true, url: false },
  robots: { follow: true, index: true, googleBot: { follow: true, index: true } },

  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: {
      default: APP_NAME,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
    // Dynamic OG images are generated by opengraph-image.tsx files
  },

  twitter: {
    card: "summary_large_image",
    title: {
      default: APP_NAME,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
    creator: "@mtakhirov",
    // Dynamic Twitter images are generated by opengraph-image.tsx files
  },

  alternates: {
    canonical: SITE_URL,
  },
};

export const viewport: Viewport = {
  colorScheme: "dark",
  themeColor: "#0a0a0a",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
