import logger from "consola";
import {
  toAbsolute,
  createFile,
  fileExists,
  collectContentMetadata,
  generateStubContent,
} from "./helpers.mjs";

/**
 * A collection of constant values used in the application.
 *
 * @constant
 * @namespace constants
 */
const constants = {
  STUB_FILE: toAbsolute("scripts/stubs/metadata.stub"),
  METADATA_FILE: toAbsolute("content/metadata.ts"),
  JSON_STRINGIFY_OPTIONS: { replacer: null, space: 2 },
};

/**
 * Creates a metadata file at the specified target path or skips the operation
 * if the file already exists. The metadata content is generated by collecting
 * content metadata and optionally transformed using specified stringification options.
 *
 * @param {string} stubPath - The path to a stub file used for generating the file content.
 * @param {string} targetPath - The path where the metadata file should be created.
 * @param {Object} stringifyOptions - Options for JSON stringification, including `replacer` and `space`.
 *
 * @return {Promise<void>} A promise that resolves when the operation is complete,
 * or skips if the file already exists.
 */
async function createOrSkipMetadataFile(
  stubPath,
  targetPath,
  stringifyOptions,
) {
  if (fileExists(targetPath)) return;

  const metadata = await collectContentMetadata();
  const metadataContent = JSON.stringify(
    metadata,
    stringifyOptions.replacer,
    stringifyOptions.space,
  );
  const stubContent = await generateStubContent(stubPath, metadataContent);
  await createFile(targetPath, stubContent);
}

/**
 * Executes the main post-installation script logic. This function attempts
 * to create or skip the metadata file based on the provided constants and
 * logs the outcome.
 *
 * @return {Promise<void>} A promise that resolves when the post-install script completes successfully,
 * or rejects if an error occurs during execution.
 */
async function main() {
  try {
    await createOrSkipMetadataFile(
      constants.STUB_FILE,
      constants.METADATA_FILE,
      constants.JSON_STRINGIFY_OPTIONS,
    );
    logger.success("Post-install script completed successfully");
  } catch (error) {
    logger.error("Failed to run post-install script", error);
  }
}

main().then();
